---
kit:
  name:    dev
  version: latest
  features:
    - external-bosh
    - cf-route-registrar
    - redis
    - mariadb
    - broker-tls
    - redis-tls
    - rabbitmq
    - rabbitmq-tls
    - rabbitmq-dual-mode
    - rabbitmq-dashboard-registration
    - rabbitmq-autoscale
    - postgresql

params:
  env:   lab-itsouvalas
  cf_skip_ssl_validation: true
  cf:
    nats_tls_only: true


  ip: 10.168.17.0
  disk_type: 10GB
  blacksmith_debug: true
  fqdn: blacksmith.it-lab.instantpc.support

instance_groups:
- name: blacksmith
  stemcell: jammy
  jobs:
    - name: rabbitmq-blacksmith-plans
      properties:
        plans:
          single-node:
            description: A dedicated RabbitMQ server, with no redundancy or replication
            limit: 7
            name: single-node
            type: standalone
            vm_type: default
            network: blacksmith
          three-node:
            description: A dedicated RabbitMQ server, with no redundancy or replication
            limit: 7
            name: three-node
            type: cluster
            vm_type: default
            network: blacksmith
    - name: mariadb-blacksmith-plans
      properties:
        plans:
          standalone:
            description: A dedicated MariaDB server, with no redundancy or replication
            limit: 7
            name: standalone
            type: standalone
            vm_type: default
            network: blacksmith
    - name: redis-blacksmith-plans
      properties:
        bosh_env: lab-itsouvalas
        environment: lab-itsouvalas
        plans:
          standalone-6:
            description: A dedicated Redis 6 server, with no redundancy or replication
            limit: 7
            name: standalone-6
            type: standalone-6
            vm_type: default
            network: blacksmith
            persist: true
          clsuter-6:
            description: A dedicated Redis 6 server, with no redundancy or replication
            limit: 7
            name: cluster-6
            type: cluster-6
            vm_type: default
            network: blacksmith
            persist: true
            masters: 1
            replicas: 1
    - name:    postgresql-blacksmith-plans
      release: postgresql-forge
      properties:
        plans:
          smalldb:
            type: standalone
            disk: 4_096
            network: blacksmith

stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest