azs:
- cloud_properties:
    data_centers:
    - clusters:
      - cluster1: {}
      name: datacenter
  name: z1
compilation:
  az: z1
  network: compilation
  reuse_compilation_vms: true
  vm_type: large
  workers: 5
disk_types:
- disk_size: 2048
  name: default
- disk_size: 2048
  name: consul
- disk_size: 10240
  name: concourse
- disk_size: 4096
  name: postgres
- disk_size: 4096
  name: blobstore
- disk_size: 1024
  name: vault
- disk_size: 16384
  name: bosh
- disk_size: 2048
  name: shield
exodus:
  bosh: lab-proto
  dated: 2023-05-16 15:00:52 +0000
  deployer: ulabuser
  domain: vault.bosh
  features: ""
  ips:
  - 10.168.0.21
  - 10.168.0.22
  - 10.168.0.23
  is_director: false
  kit_is_dev: false
  kit_name: vault
  kit_version: 2.0.0-rc.7
  use_create_env: false
  vault_base: /secret/lab/proto/vault
  version: 2.8.9
genesis:
  ci_mount: /secret/ci/
  env: lab-proto
  exodus_base: /secret/exodus/lab-proto/vault
  exodus_mount: /secret/exodus/
  exodus_path: lab-proto/vault
  min_version: 2.7.0
  secrets_base: /secret/lab/proto/vault/
  secrets_mount: /secret/
  secrets_path: lab/proto/vault
  vault_env: lab/proto
instance_groups:
- azs:
  - z1
  instances: 3
  jobs:
  - name: vault
    properties:
      safe:
        peer:
          tls:
            ca: REDACTED
            certificate: REDACTED
            key: REDACTED
        tls:
          certificate: REDACTED
          key: REDACTED
        ui: true
    release: safe
  name: vault
  networks:
  - name: vault
    static_ips:
    - 10.168.0.21
    - 10.168.0.22
    - 10.168.0.23
  persistent_disk_type: default
  stemcell: default
  vm_type: default
kit:
  features: []
  name: vault
  version: 2.0.0-rc.7
meta:
  default:
    azs:
    - z1
    - z2
    - z3
  domain: vault.bosh
  vault: /secret/lab/proto/vault
name: lab-proto-vault
networks:
- name: bosh
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: DSwitch-VM Network
    dns:
    - 8.8.8.8
    gateway: 10.168.0.1
    range: 10.168.0.16/26
    reserved:
    - 10.168.0.1 - 10.168.0.18
    - 10.168.0.21 - 10.168.0.62
    static:
    - 10.168.0.19
  type: manual
- name: vault
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: DSwitch-VM Network
    dns:
    - 8.8.8.8
    gateway: 10.168.0.1
    range: 10.168.0.16/26
    reserved:
    - 10.168.0.1 - 10.168.0.20
    - 10.168.0.25 - 10.168.0.62
    static:
    - 10.168.0.21 - 10.168.0.23
  type: manual
- name: concourse
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: DSwitch-VM Network
    dns:
    - 8.8.8.8
    gateway: 10.168.0.1
    range: 10.168.0.16/26
    reserved:
    - 10.168.0.1 - 10.168.0.24
    - 10.168.0.41 - 10.168.0.62
    static:
    - 10.168.0.25 - 10.168.0.27
  type: manual
- name: shield
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: DSwitch-VM Network
    dns:
    - 8.8.8.8
    gateway: 10.168.0.1
    range: 10.168.0.16/26
    reserved:
    - 10.168.0.1 - 10.168.0.40
    - 10.168.0.49 - 10.168.0.62
    static:
    - 10.168.0.41
  type: manual
- name: compilation
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: DSwitch-VM Network
    dns:
    - 8.8.8.8
    gateway: 10.168.0.1
    range: 10.168.0.16/26
    reserved:
    - 10.168.0.1 - 10.168.0.48
    - 10.168.0.57 - 10.168.0.62
  type: manual
params:
  availability_zones:
  - z1
  stemcell_os: ubuntu-jammy
releases:
- name: safe
  sha1: 681d650061e759ae2d7f14efcef853bee051ca5c
  url: https://bosh.io/d/github.com/cloudfoundry-community/safe-boshrelease?v=0.3.2
  version: 0.3.2
stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-120000
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-120000
vm_types:
- cloud_properties:
    cpu: 2
    disk: 4096
    ram: 4096
  name: default
- cloud_properties:
    cpu: 1
    disk: 2048
    ram: 1024
  name: small
- cloud_properties:
    cpu: 2
    disk: 4096
    ram: 4096
  name: medium
- cloud_properties:
    cpu: 4
    disk: 8192
    ram: 8192
  name: large
- cloud_properties:
    cpu: 4
    disk: 40960
    ram: 4096
  name: runtime
- cloud_properties:
    cpu: 2
    disk: 10240
    ram: 2048
  name: blacksmith