{
    "director_id": "99a672a0-eea2-47a3-5762-16c1d7cfbbf3",
    "installation_id": "4f2ed66f-1bab-4db3-5ab0-fa59c0aff7b6",
    "current_vm_cid": "vm-190cfff3-782d-4f1a-a4cd-224716e12b42",
    "current_stemcell_id": "2d332bc5-f2bc-47cc-5f40-5b6c6cdfa4a7",
    "current_disk_id": "29befa21-82a7-4c91-5674-3a480c6f4318",
    "current_release_ids": [
        "dc010b7d-f9bf-4f84-6a8b-7ae27aeb9e40",
        "3e82b72e-c843-468a-53b0-acfca2fc25f9",
        "825e44f1-9e2a-478d-6d6b-10ee93ae073f",
        "447177bd-8d12-4c49-7f53-e996df7c50d0",
        "a02dec74-132e-4222-4bb3-4d432c4db0e6",
        "717f6c0a-db18-4b83-55f1-b4377529d312"
    ],
    "current_manifest_sha": "3feb3122c68b81eb2fe9b3a9d1ec321efbf147732f8209bacb32545b3f33f640224f0141126c390ff79de194bf32a663aa5085da636f02fff49bc7113fbe5ea3",
    "disks": [
        {
            "id": "29befa21-82a7-4c91-5674-3a480c6f4318",
            "cid": "disk-54a49946-f0eb-4cbc-a15f-f0350ee16db1",
            "size": 32768,
            "cloud_properties": {
                "type": "thin"
            }
        }
    ],
    "stemcells": [
        {
            "id": "2d332bc5-f2bc-47cc-5f40-5b6c6cdfa4a7",
            "name": "bosh-vsphere-esxi-ubuntu-jammy-go_agent",
            "version": "1.64",
            "api_version": 3,
            "cid": "sc-446231dd-7964-4436-9a0a-2dd41d809925"
        }
    ],
    "releases": [
        {
            "id": "dc010b7d-f9bf-4f84-6a8b-7ae27aeb9e40",
            "name": "bosh",
            "version": "276.1.1"
        },
        {
            "id": "3e82b72e-c843-468a-53b0-acfca2fc25f9",
            "name": "bpm",
            "version": "1.1.21"
        },
        {
            "id": "825e44f1-9e2a-478d-6d6b-10ee93ae073f",
            "name": "uaa",
            "version": "76.5.0"
        },
        {
            "id": "447177bd-8d12-4c49-7f53-e996df7c50d0",
            "name": "credhub",
            "version": "2.12.17"
        },
        {
            "id": "a02dec74-132e-4222-4bb3-4d432c4db0e6",
            "name": "os-conf",
            "version": "22.1.2"
        },
        {
            "id": "717f6c0a-db18-4b83-55f1-b4377529d312",
            "name": "bosh-vsphere-cpi",
            "version": "87"
        }
    ]
}