{
    "director_id": "99a672a0-eea2-47a3-5762-16c1d7cfbbf3",
    "installation_id": "4f2ed66f-1bab-4db3-5ab0-fa59c0aff7b6",
    "current_vm_cid": "vm-0714cf99-0e46-482e-8860-be5c854da9a2",
    "current_stemcell_id": "2d332bc5-f2bc-47cc-5f40-5b6c6cdfa4a7",
    "current_disk_id": "06c658de-8b79-4caf-5fab-7f47f8736129",
    "current_release_ids": [
        "f7d173f8-5530-4af0-6a03-d2ddf836cced",
        "ec0ac8dd-cf00-4128-6d3e-27930e0c9fb1",
        "09c4b147-479e-4fbd-6229-185cd5c0418e",
        "3b2a9c7d-fd5d-401b-6206-f3976036abe2",
        "d51c1983-b23a-498c-7eed-857d593cc219",
        "46ad3f24-d042-4e40-5f1c-099ca84d6b5f"
    ],
    "current_manifest_sha": "d45f8e4dee82985ffeea2cfe73fba089392fa7b308c45e1cd55c0e3fdc32f816880db168505b98d2aae1fe839ad41295b7a15572f5635c852ee6c397767eaff6",
    "disks": [
        {
            "id": "06c658de-8b79-4caf-5fab-7f47f8736129",
            "cid": "disk-1d546c08-a80d-4412-b2ac-daa2ef09a263",
            "size": 32768,
            "cloud_properties": {
                "type": "preallocated"
            }
        }
    ],
    "stemcells": [
        {
            "id": "2d332bc5-f2bc-47cc-5f40-5b6c6cdfa4a7",
            "name": "bosh-vsphere-esxi-ubuntu-jammy-go_agent",
            "version": "1.64",
            "api_version": 3,
            "cid": "sc-446231dd-7964-4436-9a0a-2dd41d809925"
        }
    ],
    "releases": [
        {
            "id": "f7d173f8-5530-4af0-6a03-d2ddf836cced",
            "name": "bosh",
            "version": "276.1.1"
        },
        {
            "id": "ec0ac8dd-cf00-4128-6d3e-27930e0c9fb1",
            "name": "bpm",
            "version": "1.1.21"
        },
        {
            "id": "09c4b147-479e-4fbd-6229-185cd5c0418e",
            "name": "uaa",
            "version": "76.5.0"
        },
        {
            "id": "3b2a9c7d-fd5d-401b-6206-f3976036abe2",
            "name": "credhub",
            "version": "2.12.17"
        },
        {
            "id": "d51c1983-b23a-498c-7eed-857d593cc219",
            "name": "os-conf",
            "version": "22.1.2"
        },
        {
            "id": "46ad3f24-d042-4e40-5f1c-099ca84d6b5f",
            "name": "bosh-vsphere-cpi",
            "version": "87"
        }
    ]
}